
import java.net.URL;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Pantalla extends javax.swing.JFrame {

    private ArrayList<JLabel> arraycartas;
    private ArrayList<JLabel> arrayvasos;
    private ArrayList<String> arrayimagenes;
    private Random aleatorio;
    private int variablevacia;
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        variablevacia=20;
        
        
        aleatorio=new Random();
        
        arraycartas=new ArrayList<>();
        for (int i = 0; i < 12; i++) 
        {
            String r_icono = "/Imagenes/atras.png";
            ImageIcon icono = new ImageIcon(getClass().getResource(r_icono));
            JLabel v= new JLabel();
            v.setIcon(icono);
            jPanel3.add(v);
            arraycartas.add(v);
            
        }
        arrayvasos=new ArrayList<>();
        for (int i = 0; i < 12; i++) 
        {
            String r_icono = "/Imagenes/vasovacio.png";
            ImageIcon icono = new ImageIcon(getClass().getResource(r_icono));
            JLabel v= new JLabel();
            v.setIcon(icono);
            jPanel3.add(v);
            v.setName("Limpio");
            arrayvasos.add(v);
            
            
        }
        
        arrayimagenes=new ArrayList<>();
        arrayimagenes.add("Imagenes/bastos_01.png");
        arrayimagenes.add("Imagenes/bastos_02.png");
        arrayimagenes.add("Imagenes/bastos_03.png");
        arrayimagenes.add("Imagenes/bastos_04.png");
        arrayimagenes.add("Imagenes/bastos_05.png");
        arrayimagenes.add("Imagenes/bastos_06.png");
        arrayimagenes.add("Imagenes/bastos_07.png");
        arrayimagenes.add("Imagenes/bastos_08.png");
        arrayimagenes.add("Imagenes/bastos_09.png");
        arrayimagenes.add("Imagenes/bastos_10.png");
        arrayimagenes.add("Imagenes/bastos_11.png");
        arrayimagenes.add("Imagenes/bastos_12.png");
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorte = new javax.swing.JPanel();
        lNumeroJugadores = new javax.swing.JLabel();
        tfNumeroJugadores = new javax.swing.JTextField();
        bFijarJugadores = new javax.swing.JButton();
        bDescubrir = new javax.swing.JButton();
        lTurno = new javax.swing.JLabel();
        lJugador = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lMensaje = new javax.swing.JLabel();
        lMensajeInformativo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 300));

        lNumeroJugadores.setText("Número de jugadores:");
        pNorte.add(lNumeroJugadores);

        tfNumeroJugadores.setPreferredSize(new java.awt.Dimension(40, 25));
        pNorte.add(tfNumeroJugadores);

        bFijarJugadores.setText("Fijar jugadores");
        bFijarJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFijarJugadoresActionPerformed(evt);
            }
        });
        pNorte.add(bFijarJugadores);

        bDescubrir.setText("Descubrir carta");
        bDescubrir.setEnabled(false);
        bDescubrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDescubrirActionPerformed(evt);
            }
        });
        pNorte.add(bDescubrir);

        lTurno.setText("Turno del juagdor: ");
        pNorte.add(lTurno);

        lJugador.setText("-");
        pNorte.add(lJugador);

        getContentPane().add(pNorte, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lMensaje.setText("Mensaje del juego: ");
        jPanel2.add(lMensaje);

        lMensajeInformativo.setText("Descubre una carta... todavía no bebes");
        jPanel2.add(lMensajeInformativo);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(2, 12));
        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFijarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFijarJugadoresActionPerformed
        if(Integer.valueOf(tfNumeroJugadores.getText())>=2 && Integer.valueOf(tfNumeroJugadores.getText())<13)
        {
            bDescubrir.setEnabled(true);
            bFijarJugadores.setEnabled(false);
            tfNumeroJugadores.setEnabled(false);
            lJugador.setText("1");
        }
        
    }//GEN-LAST:event_bFijarJugadoresActionPerformed

    private void bDescubrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDescubrirActionPerformed
        int n_aleatorio=aleatorio.nextInt(11-0)+0;
        
        
        int contador=Integer.valueOf(lJugador.getText());
        if(contador<=Integer.valueOf(tfNumeroJugadores.getText()))
        {
            lMensajeInformativo.setText("Descubre una carta... todavía no bebes");
            String r_icono = arrayimagenes.get(n_aleatorio);
        
            arraycartas.get(contador-1).setIcon(new ImageIcon(this.getClass().getResource(r_icono)));
            
            
            
            if(variablevacia==n_aleatorio)
            {
                if(arrayvasos.get(contador-1).getName().equals("Limpio"))
                {
                    lMensajeInformativo.setText("La carta es igual que la anterior... ¡Se llena el chupito!");
                    arrayvasos.get(contador-1).setIcon(new ImageIcon(this.getClass().getResource("Imagenes/vasolleno.png")));
                    arrayvasos.get(contador-1).setName("Lleno");
                }
                else
                {
                    lMensajeInformativo.setText("La carta es igual que la anterior... ¡BEBE!");
                    arrayvasos.get(contador-1).setIcon(new ImageIcon(this.getClass().getResource("Imagenes/vasovacio.png")));
                    arrayvasos.get(contador-1).setName("Limpio");
                }
            }
            contador=contador+1;
            
            lJugador.setText(String.valueOf(contador));
             
        }
        if(Integer.valueOf(lJugador.getText())>Integer.valueOf(tfNumeroJugadores.getText()))
        {
            lJugador.setText("1");
        }
        
        variablevacia=n_aleatorio;
    }//GEN-LAST:event_bDescubrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDescubrir;
    private javax.swing.JButton bFijarJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lJugador;
    private javax.swing.JLabel lMensaje;
    private javax.swing.JLabel lMensajeInformativo;
    private javax.swing.JLabel lNumeroJugadores;
    private javax.swing.JLabel lTurno;
    private javax.swing.JPanel pNorte;
    private javax.swing.JTextField tfNumeroJugadores;
    // End of variables declaration//GEN-END:variables
}
