/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pNorte = new javax.swing.JPanel();
        lNumeroJugadores = new javax.swing.JLabel();
        tfNumeroJugadores = new javax.swing.JTextField();
        bFijarJugadores = new javax.swing.JButton();
        bDescubrir = new javax.swing.JButton();
        lTurno = new javax.swing.JLabel();
        lJugador = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lMensaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lCarta1 = new javax.swing.JLabel();
        lCarta2 = new javax.swing.JLabel();
        lCarta3 = new javax.swing.JLabel();
        lCarta4 = new javax.swing.JLabel();
        lCarta5 = new javax.swing.JLabel();
        lCarta6 = new javax.swing.JLabel();
        lCarta7 = new javax.swing.JLabel();
        lCarta8 = new javax.swing.JLabel();
        lCarta9 = new javax.swing.JLabel();
        lCarta10 = new javax.swing.JLabel();
        lCarta11 = new javax.swing.JLabel();
        lCarta12 = new javax.swing.JLabel();
        lVaso1 = new javax.swing.JLabel();
        lVaso2 = new javax.swing.JLabel();
        lVaso3 = new javax.swing.JLabel();
        lVaso4 = new javax.swing.JLabel();
        lVaso5 = new javax.swing.JLabel();
        lVaso6 = new javax.swing.JLabel();
        lVaso7 = new javax.swing.JLabel();
        lVaso8 = new javax.swing.JLabel();
        lVAso9 = new javax.swing.JLabel();
        lVaso10 = new javax.swing.JLabel();
        lVAso11 = new javax.swing.JLabel();
        lVaso12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNumeroJugadores.setText("Número de jugadores:");
        pNorte.add(lNumeroJugadores);

        tfNumeroJugadores.setPreferredSize(new java.awt.Dimension(40, 25));
        pNorte.add(tfNumeroJugadores);

        bFijarJugadores.setText("Fijar jugadores");
        pNorte.add(bFijarJugadores);

        bDescubrir.setText("Descubrir carta");
        pNorte.add(bDescubrir);

        lTurno.setText("Turno del juagdor: ");
        pNorte.add(lTurno);

        lJugador.setText("-");
        pNorte.add(lJugador);

        getContentPane().add(pNorte, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        lMensaje.setText("Mensaje del juego: ");
        jPanel2.add(lMensaje);

        jLabel2.setText("Descubre una carta... todavía no bebes");
        jPanel2.add(jLabel2);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(2, 12));

        lCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta1);

        lCarta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta2);

        lCarta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta3);

        lCarta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta4);

        lCarta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta5);

        lCarta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta6);

        lCarta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta7);

        lCarta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta8);

        lCarta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta9);

        lCarta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta10);

        lCarta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta11);

        lCarta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jPanel3.add(lCarta12);

        lVaso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso1);

        lVaso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso2);

        lVaso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso3);

        lVaso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso4);

        lVaso5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso5);

        lVaso6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso6);

        lVaso7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso7);

        lVaso8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso8);

        lVAso9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVAso9);

        lVaso10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso10);

        lVAso11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVAso11);

        lVaso12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vasovacio.png"))); // NOI18N
        jPanel3.add(lVaso12);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDescubrir;
    private javax.swing.JButton bFijarJugadores;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lCarta1;
    private javax.swing.JLabel lCarta10;
    private javax.swing.JLabel lCarta11;
    private javax.swing.JLabel lCarta12;
    private javax.swing.JLabel lCarta2;
    private javax.swing.JLabel lCarta3;
    private javax.swing.JLabel lCarta4;
    private javax.swing.JLabel lCarta5;
    private javax.swing.JLabel lCarta6;
    private javax.swing.JLabel lCarta7;
    private javax.swing.JLabel lCarta8;
    private javax.swing.JLabel lCarta9;
    private javax.swing.JLabel lJugador;
    private javax.swing.JLabel lMensaje;
    private javax.swing.JLabel lNumeroJugadores;
    private javax.swing.JLabel lTurno;
    private javax.swing.JLabel lVAso11;
    private javax.swing.JLabel lVAso9;
    private javax.swing.JLabel lVaso1;
    private javax.swing.JLabel lVaso10;
    private javax.swing.JLabel lVaso12;
    private javax.swing.JLabel lVaso2;
    private javax.swing.JLabel lVaso3;
    private javax.swing.JLabel lVaso4;
    private javax.swing.JLabel lVaso5;
    private javax.swing.JLabel lVaso6;
    private javax.swing.JLabel lVaso7;
    private javax.swing.JLabel lVaso8;
    private javax.swing.JPanel pNorte;
    private javax.swing.JTextField tfNumeroJugadores;
    // End of variables declaration//GEN-END:variables
}
